// Hospital-management-system/Frontend/src/components/DashboardLayout.jsx
import { motion } from "framer-motion";

function DashboardLayout({ title, children }) {
  return (
    <div className="min-h-screen flex bg-[#030712] text-slate-200 selection:bg-emerald-500/30">
      
      

      {/* --- MAIN INTERFACE --- */}
      <main className="flex-1 flex flex-col min-w-0 overflow-hidden">
        
        {/* TOP HEADER */}
       

        {/* SCROLLABLE CONTENT AREA */}
        <div className="flex-1 mt-20 overflow-y-auto p-6 md:p-10 scrollbar-hide">
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, ease: "easeOut" }}
            className="max-w-7xl mx-auto"
          >
            {/* The white card container is now replaced with a transparent "Stage" */}
            <section className="relative  overflow-hidden rounded-2xl bg-white/5 border border-white/10 backdrop-blur-md p-8 min-h-[400px]">
              {/* Background Glow Effect */}
             
              
              {children}
            </section>
          </motion.div>
        </div>
      </main>
    </div>
  );
}

export default DashboardLayout;

// Hospital-management-system/medicare-angular/src/app/shared/components/dashboard-layout/dashboard-layout.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-dashboard-layout',
  standalone: false,
  templateUrl: './dashboard-layout.component.html',
})
export class DashboardLayoutComponent {
  @Input() title = '';
}

<div class="min-h-screen flex bg-[#030712] text-slate-200">
  <main class="flex-1 flex flex-col min-w-0 overflow-hidden">
    <div class="flex-1 mt-20 overflow-y-auto p-6 md:p-10 scrollbar-hide">
      <div class="max-w-7xl mx-auto">
        <section class="relative overflow-hidden rounded-2xl bg-white/5 border border-white/10 backdrop-blur-md p-8 min-h-[400px]">
          <ng-content></ng-content>
        </section>
      </div>
    </div>
  </main>
</div>
