// Hospital-management-system/Frontend/src/components/Navbar.jsx
import { Link, useNavigate } from "react-router-dom";
import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import logo from "../assets/betterlife-logo.png";

function Navbar() {
  const [open, setOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  const navigate = useNavigate();
  const token = localStorage.getItem("token");
  const role = localStorage.getItem("role");

  useEffect(() => {
    const handleScroll = () => setScrolled(window.scrollY > 10);
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  const handleLogout = () => {
    localStorage.clear();
    navigate("/login");
  };

  const menuVariants = {
    hidden: { opacity: 0, scale: 0.9, y: -20, rotateX: -15 },
    visible: { 
      opacity: 1, 
      scale: 1, 
      y: 0, 
      rotateX: 0,
      transition: { type: "spring", stiffness: 200, damping: 20, staggerChildren: 0.1 } 
    },
    exit: { opacity: 0, scale: 0.9, y: -20, transition: { duration: 0.2 } }
  };

  const itemVariants = {
    hidden: { opacity: 0, x: -10 },
    visible: { opacity: 1, x: 0 }
  };

  return (
    <nav className={`fixed top-0 z-50 w-full px-4 transition-all duration-500 ${scrolled ? "py-3" : "py-6"}`}>
      
      <motion.div 
        initial={{ y: -100 }}
        animate={{ y: 0 }}
        className={`max-w-7xl mx-auto px-6 py-3 flex justify-between items-center rounded-3xl border transition-all duration-500
          ${scrolled 
            ? "bg-white/40 backdrop-blur-xl border-white/40 shadow-[0_8px_32px_0_rgba(31,38,135,0.15)]" 
            : "bg-blue-600/10 backdrop-blur-md border-white/20 shadow-none"
          }`}
      >
        
        {/* Logo */}
        <motion.div whileHover={{ scale: 1.02 }} className="flex items-center gap-3 cursor-pointer">
          <Link to="/" className="flex items-center gap-3 group">
            <div className="relative">
              <motion.div 
                animate={{ scale: [1, 1.2, 1] }}
                transition={{ duration: 2, repeat: Infinity }}
                className="absolute inset-0 bg-blue-400/30 blur-xl rounded-full"
              />
              <img src={logo} alt="BetterLife" className="h-10 relative z-10" />
            </div>
            <span className={`text-2xl font-black tracking-tighter transition-colors duration-300 ${scrolled ? "text-slate-800" : "text-white"}`}>
              Better<span className="text-blue-500 group-hover:text-blue-400 transition-colors">Life</span>
            </span>
          </Link>
        </motion.div>

        {/* Desktop Menu */}
        <div className="hidden md:flex gap-1 items-center">
          {["Home", "About", "Services", "Contact"].map((item) => (
            <Link 
              key={item} 
              to={item === "Home" ? "/" : `/${item.toLowerCase()}`}
              className={`px-5 py-2 rounded-full text-sm font-bold transition-all relative group
                ${scrolled ? "text-slate-600 hover:text-blue-600" : "text-white/80 hover:text-white"}`}
            >
              <span className="relative z-10">{item}</span>
              <motion.span 
                className="absolute inset-0 bg-blue-500/10 rounded-full opacity-0 group-hover:opacity-100 transition-opacity"
                layoutId="hoverBg"
              />
            </Link>
          ))}

          <div className="w-[1px] h-6 bg-slate-400/20 mx-4" />

          <div className="flex items-center gap-4">
            {!token ? (
              <>
                <Link to="/login" className={`text-sm font-bold transition-colors ${scrolled ? "text-slate-700 hover:text-blue-600" : "text-white hover:text-blue-200"}`}>
                  Sign In
                </Link>
              </>
            ) : (
              <div className="flex items-center gap-3">
                <motion.button
                  whileHover={{ scale: 1.05 }}
                  onClick={() => navigate(`/${role}`)}
                  className="flex items-center gap-2 bg-slate-900/90 hover:bg-black text-white px-5 py-2.5 rounded-2xl font-bold backdrop-blur-md transition-all shadow-lg"
                >
                  Dashboard
                </motion.button>
                <button
                  onClick={handleLogout}
                  className="p-2 group rounded-xl hover:bg-red-50 transition-colors"
                >
                  Logout
                </button>
              </div>
            )}
          </div>
        </div>

        {/* Mobile Toggle */}
        <button className="md:hidden" onClick={() => setOpen(!open)}>
          ☰
        </button>
      </motion.div>

      {/* Mobile Menu */}
      <AnimatePresence>
        {open && (
          <motion.div
            variants={menuVariants}
            initial="hidden"
            animate="visible"
            exit="exit"
            className="absolute top-24 left-4 right-4 md:hidden rounded-[2rem] bg-white p-8"
          >
            <div className="flex flex-col gap-4">
              {["Home", "About", "Services", "Contact"].map((item) => (
                <Link 
                  key={item}
                  to={item === "Home" ? "/" : `/${item.toLowerCase()}`}
                  onClick={() => setOpen(false)}
                >
                  {item}
                </Link>
              ))}

              {!token && (
                <Link to="/login" onClick={() => setOpen(false)}>
                  Login
                </Link>
              )}

              {token && (
                <button onClick={handleLogout}>
                  Logout
                </button>
              )}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </nav>
  );
}

export default Navbar;

// Hospital-management-system/medicare-angular/src/app/shared/components/navbar/navbar.component.ts
import { Component, OnInit, HostListener } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../../../core/services/auth.service';

@Component({
  selector: 'app-navbar',
  standalone: false,
  templateUrl: './navbar.component.html',
})
export class NavbarComponent implements OnInit {
  open = false;
  scrolled = false;

  navLinks = [
    { label: 'Home', path: '/' },
    { label: 'About', path: '/about' },
    { label: 'Services', path: '/services' },
    { label: 'Contact', path: '/contact' },
  ];

  constructor(public authService: AuthService, private router: Router) {}

  ngOnInit(): void {}

  @HostListener('window:scroll')
  onScroll(): void {
    this.scrolled = window.scrollY > 10;
  }

  handleLogout(): void {
    this.authService.logout();
  }

  goToDashboard(): void {
    const role = this.authService.getRole();
    if (role) this.router.navigate([`/${role}`]);
  }
}

<nav [class]="'fixed top-0 z-50 w-full px-4 transition-all duration-500 ' + (scrolled ? 'py-4' : 'py-8')">
  <div [class]="'max-w-7xl mx-auto px-6 py-3 flex justify-between items-center rounded-[2.5rem] border transition-all duration-500 ' + (scrolled ? 'bg-white/40 backdrop-blur-2xl border-white/40 shadow-[0_20px_50px_rgba(0,0,0,0.1)]' : 'bg-blue-600/5 backdrop-blur-md border-white/20')">

    <!-- Logo -->
    <a routerLink="/" class="flex items-center gap-3 group">
      <div class="relative">
        <div class="absolute inset-0 bg-blue-400 blur-xl rounded-full opacity-30"></div>
        <div class="relative z-10 w-10 h-10 bg-blue-600 rounded-xl flex items-center justify-center">
          <span class="text-white font-black text-lg">B</span>
        </div>
      </div>
      <span [class]="'text-2xl font-black tracking-tighter transition-colors duration-300 ' + (scrolled ? 'text-slate-800' : 'text-white')">
        Better<span class="text-blue-500 group-hover:text-blue-400 transition-colors">Life</span>
      </span>
    </a>

    <!-- Desktop Menu -->
    <div class="hidden md:flex gap-1 items-center">
      <a *ngFor="let item of navLinks"
         [routerLink]="item.path"
         routerLinkActive="text-blue-500"
         [class]="'px-5 py-2 rounded-full text-sm font-bold transition-all hover:bg-blue-500/10 ' + (scrolled ? 'text-slate-600 hover:text-blue-600' : 'text-white/80 hover:text-white')">
        {{ item.label }}
      </a>

      <div class="w-[1px] h-6 bg-slate-400/20 mx-4"></div>

      <ng-container *ngIf="!authService.isLoggedIn(); else loggedIn">
        <a routerLink="/login"
           [class]="'px-6 py-2.5 rounded-2xl text-sm font-bold transition-all border ' + (scrolled ? 'bg-slate-900 text-white border-transparent shadow-lg' : 'bg-white/10 text-white border-white/20 backdrop-blur-md')">
          Sign In
        </a>
      </ng-container>

      <ng-template #loggedIn>
        <div class="flex items-center gap-3">
          <button (click)="goToDashboard()"
                  class="flex items-center gap-2 bg-slate-900/90 hover:bg-black text-white px-6 py-2.5 rounded-2xl font-bold backdrop-blur-xl transition-all border border-white/10">
            <span class="w-2 h-2 bg-emerald-400 rounded-full animate-pulse"></span>
            Dashboard
          </button>
          <button (click)="handleLogout()"
                  class="px-4 py-2.5 rounded-2xl text-sm font-bold transition-all text-slate-500 border border-transparent hover:border-red-500/20 hover:text-red-400">
            Logout
          </button>
        </div>
      </ng-template>
    </div>

    <!-- Mobile Toggle -->
    <button class="md:hidden w-11 h-11 flex flex-col items-center justify-center gap-1.5 rounded-xl border bg-white/10 border-white/20"
            (click)="open = !open">
      <span [class]="'w-6 h-0.5 rounded-full transition-all ' + (scrolled ? 'bg-slate-800' : 'bg-white')"></span>
      <span [class]="'w-6 h-0.5 rounded-full transition-all ' + (scrolled ? 'bg-slate-800' : 'bg-white') + (open ? ' opacity-0' : '')"></span>
      <span [class]="'w-6 h-0.5 rounded-full transition-all ' + (scrolled ? 'bg-slate-800' : 'bg-white')"></span>
    </button>
  </div>

  <!-- Mobile Menu -->
  <div *ngIf="open"
       class="absolute top-28 left-4 right-4 md:hidden rounded-[2.5rem] bg-white/70 backdrop-blur-3xl border border-white/50 p-8 shadow-2xl">
    <div class="flex flex-col gap-4">
      <a *ngFor="let item of navLinks"
         [routerLink]="item.path"
         (click)="open = false"
         class="text-2xl font-black text-slate-800 hover:text-blue-600 transition-colors block">
        {{ item.label }}
      </a>

      <div class="h-[1px] bg-slate-200/50 my-2"></div>

      <ng-container *ngIf="!authService.isLoggedIn(); else mobileLoggedIn">
        <a routerLink="/login" (click)="open = false"
           class="flex items-center justify-center w-full py-4 bg-blue-600 text-white rounded-2xl font-bold shadow-lg">
          Get Started
        </a>
      </ng-container>
      <ng-template #mobileLoggedIn>
        <button (click)="handleLogout()"
                class="w-full py-4 bg-red-50 text-red-600 rounded-2xl font-bold border border-red-100">
          Logout Account
        </button>
      </ng-template>
    </div>
  </div>
</nav>
